[package]
name = "slotted-for-lean"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
slotted-egraphs = { git = "https://github.com/marcusrossel/slotted-egraphs.git", features = ["explanations"] }
libc = "0.2"