[package]
name = "egg-for-lean"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
slotted-egraphs = { path = "../../slotted-egraphs", features = ["explanations"] }
indexmap = "1.8.1"
libc = "0.2"